### PR TITLE
rebuild for python310 + add osxarm + fix numpy pin + fix __cuda

### LINKED ISSUE #3: fix numpy pin
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

current pin is too restrictive; pin_compatible should only be used if numpy is in host, otherwise you end up pinning hard against latest+, i.e. 1.23+

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

### LINKED ISSUE #4: actually add __cuda
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I was wrong, we should have __cuda in run here.

### Installed packages

```shell
m/a
```

### Environment info

```shell
m/a
```

### PR DESCRIPTION
**Pull request by ngam**
fix #4 
fix #3
close #1 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
there is no headless on conda(-forge). Just depend on on `opencv` or `py-opencv` (loosen pinnings if it is only the python library you deal with). A headless version has been proposed, but it isn't super obvious how to maintain it. The workarounds in the pip community hurt my head when they try to depend on opencv. https://github.com/conda-forge/opencv-feedstock/issues/293

Ultimately, numpy pinnings are somewhat tricky. I'm somewhat affraid that you are depending on them indirectly through the large dependencies that are being pulled in for "safety".

@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
@ngam have you been able to successfully install this using mamba? I know that conda might ignore the run_exports (if the name clashes with a requirement). That is why you seem to require the addition of `__cuda`.

**Comment by hmaarrfk** [comment]
```
try:
    # OpenCV installed via conda.
    import cv2  # NOQA: F401
    major, minor, *rest = cv2.__version__.split('.')
    if int(major) < 3:
        raise RuntimeError(
            f'OpenCV >=3 is required but {cv2.__version__} is installed')
except ImportError:
    # If first not installed install second package
    CHOOSE_INSTALL_REQUIRES = [('opencv-python-headless>=3',
                                'opencv-python>=3')]
    for main, secondary in CHOOSE_INSTALL_REQUIRES:
        install_requires.append(choose_requirement(main, secondary))
```
should be patched out for the OSX cross compilation build.

**Comment by apatsekin** [comment]
Yeah totally, thanks both of you!

btw: I also tested on a box with GPU  version with `__cuda` that I built using `build_locally.py`. I didn't test it after we removed `__cuda` though.

**Review by apatsekin — APPROVED** [review]

**Comment by apatsekin** [comment]
btw automerge doesn't work as I thought

**Comment by hmaarrfk** [comment]
it does. it just takes a minute or two (or 60) for the bot to come around.

**Pull request merged**
